### ISSUE TITLE
Create (Docker) Image

### ISSUE THREAD

**Issue by genofire** [silkeh/alertmanager_matrix#6]

**Comment by silkeh** [comment]
Please add a description describing why you want a Docker image.

**Comment by silkeh** [comment]
The Docker image can be found on Docker Hub as [silkeh/alertmanager_matrix](https://hub.docker.com/r/silkeh/alertmanager_matrix).

**Comment by genofire** [comment]
Thanks

**Comment by genofire** [comment]
For validating HTTPS / TLS connection (to Homeserver) we need CA-Certs

Easy to solve, by just copy from builder (were an OS with CA-Certs is inside), copy the `/etc/ssl/certs/ca-certificates.crt` to the new SCRETCH-Container (which does not contain anything) like the binary.

https://github.com/silkeh/alertmanager_matrix/blob/01cca133a7c2bd641044ce97d0538f7be1a51ed8/Dockerfile#L9

---
EDIT: Builder is an alpine, there is the path `/etc/ssl/cert.pem` ...

for fast finding of golang COPY from `/etc/ssl/cert.pem` to `/etc/ssl/certs/ca-certificates.crt` - see: https://go.dev/src/crypto/x509/root_linux.go

**Comment by genofire** [comment]
Implemented here: 
https://gitlab.com/silkeh/alertmanager_matrix/-/merge_requests/4

Do you prefer gitlab or github for issues, mr/pr ...

**Comment by silkeh** [comment]
Thanks!

> Do you prefer gitlab or github for issues, mr/pr ...

Both are acceptable currently. The GitLab repo is mainly there because I prefer GitLab CI.
