### ISSUE TITLE
missing new release

### ISSUE THREAD

**Issue by genofire** [silkeh/alertmanager_matrix#7]
for that commit:

https://github.com/silkeh/alertmanager_matrix/commit/a5e6882472bbecebef81c0fe8bf3a90d2093555b

you have no docker container released:
https://hub.docker.com/r/silkeh/alertmanager_matrix/tags

----

because you have not mirrored to:
https://gitlab.com/silkeh/alertmanager_matrix

....

also a stable release tag would be nice:
https://gitlab.com/silkeh/alertmanager_matrix/-/merge_requests/5

---
i still love your bot, really nice work ;)

**Comment by silkeh** [comment]
Sorry about that. I have fixed the generation and pushing of tags. They should always show up in the future, but let me know if this isn't the case.

Additionally, the images are now versioned and pushed using each version component (eg: `0`, `0.4` and `0.4.2`).
